language: python

python:
  - "3.6"

install:
  - pip install mkdocs mkdocs-material

script:
  - git clone https://gitee.com/hitsz-lab/Computer-Arch.git
  - mv Computer-Arch site
  - mkdocs build
  - git config user.name "Computer-Arch"
  - git config user.email "qiujieting@163.com"
  - cd site
  - git add * 
  - git commit -m "site updated by Travis CI"
  - git push https://${giteeusername}:${giteepwd}@gitee.com/hitsz-lab/Computer-Arch.git master

branches:
  only:
    - master